url: https://gouvernance.noesya.coop
title: Gouvernance Noesya
subdomain: Gouvernance
lang: fr

theme: jekyll-theme-noesya

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: "years"
    values:
      layout: "year"
  -
    scope:
      path: ""
      type: "documents"
    values:
      layout: "document"

collections:
  pages:
    output: true
  documents:
    output: true
  categories:
    output: true
    permalink: /documents/:title
  years:
    output: true
    permalink: /documents/:title

plugins:
  - jekyll-minifier
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
